# Generated by Django 2.1.1 on 2018-10-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20181003_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Py_Log_mssql',
            fields=[
                ('pylog_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pylog_etapa_id', models.IntegerField()),
                ('pylog_desc', models.CharField(max_length=200)),
                ('pylog_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': '[DW].[PY_LOG]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sistema_Reload_mssql',
            fields=[
                ('sistema_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sistema_database', models.CharField(max_length=50)),
                ('sistema_server', models.CharField(max_length=15)),
                ('sistema_dw_desc', models.CharField(max_length=50)),
                ('sistema_datetime_start', models.DateTimeField()),
                ('sistema_datetime_finish', models.DateTimeField()),
                ('sistema_erro_flag', models.BooleanField()),
            ],
            options={
                'db_table': '[DW].[SISTEMA_RELOAD]',
                'managed': False,
            },
        ),
    ]
